# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# Mod properties
mod_version=3.0.0
maven_group=com.firemerald.additionalplacements
archives_name=additionalplacements
enabled_platforms=fabric,neoforge
# Minecraft properties
minecraft_version=1.21.4
# Dependencies
fabric_loader_version=0.18.5
fabric_api_version=0.119.4+1.21.4
neoforge_version=21.4.157

parchment_version=1.21.4:2025.03.23
forge_config_api_port_version=21.4.3