loom.platform=neoforge

//doubleslabs_version=1.21.1-0.4.1
balm_version=21.0.41+neoforge-1.21.1
kleeslabs_version=21.1.3+neoforge-1.21.1
//continuity_version=3.0.0+1.21
ctm_file=5587515

//create_mc_version=1.21.1
//create_version=6.0.9-215
//ponder_version=1.0.81
//flywheel_version=1.0.6
//registrate_version=MC1.21-1.3.0+67